HAI 1.2
CAN HAS STDIO?
I HAS A COUNT
I HAS A GAME
BTW LOLCODE IZ KIND OF DUMB SO HAV 2 CHOMP AFTER EACH STDIN
I HAS A CHOMP
GIMMEH COUNT
COUNT IS NOW A NUMBR
GIMMEH CHOMP
IM IN YR LOOP
  GIMMEH GAME
  GIMMEH CHOMP
  GAME IS NOW A NUMBR
  I HAS A REMAINDER ITZ MOD OF GAME AN 2
  BOTH SAEM GAME AN 1, O RLY?
    YA RLY
      VISIBLE "Kitty"
    MEBBE BOTH SAEM REMAINDER AN 0
      VISIBLE "Kitty"
    NO WAI
      VISIBLE "Katty"
  OIC
  COUNT R DIFF OF COUNT AN 1
  BOTH SAEM COUNT AN 0, O RLY?
  YA RLY, GTFO, OIC
IM OUTTA YR LOOP
KTHXBYE
